examen2/examen2/NFLPR/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path('core/', include("core.urls")),
]

examen2/examen2/core/urls.py
from django.urls import path

from core import views

app_name = "core"

urlpatterns = [
    path('create/ciudades/', views.CreateCiudades.as_view(), name="create_ciudades"),
    path('list/ciudades', views.ListCiudades.as_view(), name="list_ciudades"),
    path('detail/ciudades/<int:pk>/', views.DetailCiudades.as_view(), name="detail_ciudades"),
    path('update/ciudades/<int:pk>/', views.UpdateCiudades.as_view(), name="update_ciudades"),
    path('delete/ciudades/<int:pk>/', views.DeleteCiudades.as_view(), name="delete_ciudades"),

    ####URLS EQUIPOS

    path('create/equipos/', views.CrearEquipo.as_view(), name="create_equipos"),
    path('list/equipos/', views.ListarEquipos.as_view(), name="list_equipos"),
    path('detail/equipos/<int:pk>/', views.DetalleEquipo.as_view(), name="detail_equipos"),
    path('update/equipos/<int:pk>/', views.ActualizarEquipo.as_view(), name="update_equipos"),
    path('delete/equipos/<int:pk>/', views.EliminarEquipo.as_view(), name="delete_equipos"),

    ###URLS ESTADIOS

    path('create/estadios/', views.CrearEstadio.as_view(), name="create_estadios"),
    path('list/estadios/', views.ListarEstadios.as_view(), name="list_estadios"),
    path('detail/estadios/<int:pk>/', views.DetalleEstadio.as_view(), name="detail_estadios"),
    path('update/estadios/<int:pk>/', views.ActualizarEstadio.as_view(), name="update_estadios"),
    path('delete/estadios/<int:pk>/', views.EliminarEstadio.as_view(), name="delete_estadios"),

]

examen2/examen2/core/models.py
from django.db import models
from django.contrib.auth.models import User

class Ciudades(models.Model):
    nombre = models.CharField(max_length=100)
    pais = models.CharField(max_length=100)

    def __str__(self):
        return self.nombre

class Estadios(models.Model):
    nombre = models.CharField(max_length=100)
    ciudad = models.ForeignKey(Ciudades, on_delete=models.CASCADE)
    capacidad = models.PositiveIntegerField()

    def __str__(self):
        return self.nombre

class Equipos(models.Model):
    nombre = models.CharField(max_length=100)
    liga = models.CharField(max_length=100)
    fundacion = models.DateField()

    def __str__(self):
        return self.nombre

examen2/examen2/core/forms.py
from django import forms
from .models import Ciudades, Equipos, Estadios

### C I U D A D E S

class CiudadesForm(forms.ModelForm):
    class Meta:
        model = Ciudades
        fields = '__all__'


        widgets = {
            "nombre": forms.TextInput(attrs={"type": "text", "class": "form-control", "placeholder": "Nombre de la ciudad","style": "background-color: gray;"}),
            "pais": forms.TextInput(attrs={"type": "text", "class": "form-control", "placeholder": "País de la ciudad", "style": "background-color: gray;"})

        }


class UpdateCiudadesForm(forms.ModelForm):
    class Meta:
        model = Ciudades
        fields = '__all__'

        widgets = {
            "nombre": forms.TextInput(attrs={"type": "text", "class": "form-control", "placeholder": "Nombre de la ciudad" , "style": "background-color: gray;"}),
            "pais": forms.TextInput(attrs={"type": "text", "class": "form-control", "placeholder": "País de la ciudad", "style": "background-color: gray;" }),
        }



### E Q U I P O S

class EquiposForm(forms.ModelForm):
    class Meta:
        model = Equipos
        fields = '__all__'  

        widgets = {
            "nombre": forms.TextInput(attrs={"type": "text", "class": "form-control", "placeholder": "Nombre del equipo", "style": "background-color: gray;"}),
            "liga": forms.TextInput(attrs={"type": "text", "class": "form-control", "placeholder": "Liga del equipo", "style": "background-color: gray;"}),
            "fundacion": forms.DateInput(attrs={"type": "date", "class": "form-control" , "style": "background-color: gray;"}),
        }

class UpdateEquiposForm(forms.ModelForm):
    class Meta:
        model = Equipos
        fields = '__all__'  #

        widgets = {
            "nombre": forms.TextInput(attrs={"type": "text", "class": "form-control", "placeholder": "Nombre del equipo", "style": "background-color: gray;"}),
            "liga": forms.TextInput(attrs={"type": "text", "class": "form-control", "placeholder": "Liga del equipo", "style": "background-color: gray;"}),
            "fundacion": forms.DateInput(attrs={"type": "date", "class": "form-control"}),
        }

### E S T A D I O S

class EstadiosForm(forms.ModelForm):
    class Meta:
        model = Estadios
        fields = '__all__'  

        widgets = {
            "nombre": forms.TextInput(attrs={"type": "text", "class": "form-control", "placeholder": "Nombre del estadio", "style": "background-color: gray;"}),
            "ciudad": forms.Select(attrs={"class": "form-control", "style": "background-color: gray;"}),
            "capacidad": forms.NumberInput(attrs={"type": "number", "class": "form-control", "placeholder": "Capacidad del estadio", "style": "background-color: gray;"}),
        }

class UpdateEstadiosForm(forms.ModelForm):
    class Meta:
        model = Estadios
        fields = '__all__'  

        widgets = {
            "nombre": forms.TextInput(attrs={"type": "text", "class": "form-control", "placeholder": "Nombre del estadio", "style": "background-color: gray;"}),
            "ciudad": forms.Select(attrs={"class": "form-control"}),
            "capacidad": forms.NumberInput(attrs={"type": "number", "class": "form-control", "placeholder": "Capacidad del estadio", "style": "background-color: gray;"}),
        }

examen2/examen2/core/views.py
from django.shortcuts import render
from django.views import generic
from django.urls import reverse_lazy
from .models import Ciudades, Equipos, Estadios  
from .forms import CiudadesForm, UpdateCiudadesForm  
from .forms import EquiposForm, UpdateEquiposForm
from .forms import EstadiosForm, UpdateEstadiosForm

# Create your views here.

# Create
class CreateCiudades(generic.CreateView):
    template_name = "core/create_ciudades.html"
    model = Ciudades  
    form_class = CiudadesForm  
    success_url = reverse_lazy("core:list_ciudades")

# Retrieve
# List


class ListCiudades(generic.View):
    template_name = "core/list_ciudades.html"
    context = {}

    def get(self, request, *args, **kwargs):
        ciudades = Ciudades.objects.all()  
        self.context = {
            "ciudades": ciudades
        }
        return render(request, self.template_name, self.context)


# Detail
class DetailCiudades(generic.View):
    template_name = "core/detail_ciudades.html"
    context = {}

    def get(self, request, pk, *args, **kwargs):
        ciudad = Ciudades.objects.get(pk=pk)  
        self.context = {
            "ciudad": ciudad
        }
        return render(request, self.template_name, self.context)

# Update
class UpdateCiudades(generic.UpdateView):
    template_name = "core/update_ciudades.html"
    model = Ciudades  
    form_class = UpdateCiudadesForm  
    success_url = reverse_lazy("core:list_ciudades")

# Delete
class DeleteCiudades(generic.DeleteView):
    template_name = "core/delete_ciudades.html"
    model = Ciudades  
    success_url = reverse_lazy("core:list_ciudades")




### E Q U I P O S


class CrearEquipo(generic.CreateView):
    template_name = "core/create_equipos.html"
    model = Equipos  
    form_class = EquiposForm  
    success_url = reverse_lazy("core:list_equipos")


class ListarEquipos(generic.View):
    template_name = "core/list_equipos.html"
    context = {}

    def get(self, request, *args, **kwargs):
        equipos = Equipos.objects.all()  
        self.context = {
            "equipos": equipos
        }
        return render(request, self.template_name, self.context)


class DetalleEquipo(generic.View):
    template_name = "core/detail_equipos.html"
    context = {}

    def get(self, request, pk, *args, **kwargs):
        equipo = Equipos.objects.get(pk=pk)  
        self.context = {
            "equipo": equipo
        }
        return render(request, self.template_name, self.context)


class ActualizarEquipo(generic.UpdateView):
    template_name = "core/update_equipos.html"
    model = Equipos  
    form_class = UpdateEquiposForm  
    success_url = reverse_lazy("core:list_equipos")

class EliminarEquipo(generic.DeleteView):
    template_name = "core/delete_equipos.html"
    model = Equipos  
    success_url = reverse_lazy("core:list_equipos")



### E S T A D I O S

class CrearEstadio(generic.CreateView):
    template_name = "core/create_estadios.html"
    model = Estadios  
    form_class = EstadiosForm  
    success_url = reverse_lazy("core:list_estadios")

class ListarEstadios(generic.View):
    template_name = "core/list_estadios.html"
    context = {}

    def get(self, request, *args, **kwargs):
        estadios = Estadios.objects.all()
        self.context = {
            "estadios": estadios
        }
        return render(request, self.template_name, self.context)

class DetalleEstadio(generic.View):
    template_name = "core/detail_estadios.html"
    context = {}

    def get(self, request, pk, *args, **kwargs):
        estadio = Estadios.objects.get(pk=pk)
        self.context = {
            "estadio": estadio
        }
        return render(request, self.template_name, self.context)

class ActualizarEstadio(generic.UpdateView):
    template_name = "core/update_estadios.html"
    model = Estadios  
    form_class = UpdateEstadiosForm  
    success_url = reverse_lazy("core:list_estadios")

class EliminarEstadio(generic.DeleteView):
    template_name = "core/delete_estadios.html"
    model = Estadios  
    success_url = reverse_lazy("core:list_estadios")

examen2/examen2/templates/core/create_ciudades.html
{% extends "base/base.html" %}

{% block title %}
  CREAR VISTA DE CIUDAD
{% endblock title %}

{% block content %}
    <form action="" method="post" class="form" style="margin: 100px; color: rgb(0, 17, 112);">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-outline-success form-control" style="background-color: rgb(0, 70, 0); color: rgb(255, 255, 255);">Crear Ciudad </button>
        <br>
        <a href="{% url 'core:list_ciudades' %}" class="btn btn-outline-warning form-control" style="background-color: rgb(172, 187, 0); color: rgb(255, 255, 255);" >Cancelar</a>
    </form>
{% endblock content %}

examen2/examen2/templates/core/create_estadios.html
{% extends "base/base.html" %}

{% block title %}
  CREAR VISTA DE ESTADIOS
{% endblock title %}

{% block content %}
    <form action="" method="post" class="form" style="margin: 100px; color: rgb(0, 17, 112);">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-outline-success form-control" style="background-color: rgb(0, 70, 0); color: rgb(255, 255, 255);">Crear Estadio </button>
        <br>
        <a href="{% url 'core:list_estadios' %}" class="btn btn-outline-warning form-control" style="background-color: rgb(172, 187, 0); color: rgb(255, 255, 255);" >Cancelar</a>
    </form>
{% endblock content %}

examen2/examen2/templates/core/delete_ciudades.html
{% extends "base/base.html" %}

{% block title %}
ELIMINAR VISTA DE CIUDAD
{% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <div class="card text-white bg-primary mb-3" style="max-width: 20rem;">
            <div class="card-header">   Eliminar Ciudad</div>
            <div class="card-body">
              <h4 class="card-title">{{ object.ciudades_name }}</h4>
              <p>¿Realmente deseas eliminar esta ciudad?</p>
              <button type="submit" class="btn btn-danger">Eliminar Ciudad</button>
              <a href="{% url 'core:list_ciudades' %}" class="btn btn-warning">Cancel</a>
            </div>
          </div>
        
        
        
    </form>
{% endblock content %}  

examen2/examen2/templates/core/delete_equipos.html
{% extends "base/base.html" %}

{% block title %}
ELIMINAR VISTA DE EQUIPO
{% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <div class="card text-white bg-primary mb-3" style="max-width: 20rem;">
            <div class="card-header">   Eliminar Equipo</div>
            <div class="card-body">
              <h4 class="card-title">{{ object.equipo_name }}</h4>
              <p>¿Realmente deseas eliminar este equipo?</p>
              <button type="submit" class="btn btn-danger">Eliminar Equipo</button>
              <a href="{% url 'core:list_equipos' %}" class="btn btn-warning">Cancel</a>
            </div>
          </div>
        
        
        
    </form>
{% endblock content %}  

examen2/examen2/templates/core/delete_estadios.html
{% extends "base/base.html" %}

{% block title %}
ELIMINAR VISTA DE ESTADIOS
{% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <div class="card text-white bg-primary mb-3" style="max-width: 20rem;">
            <div class="card-header">   Eliminar Estadio</div>
            <div class="card-body">
              <h4 class="card-title">{{ object.estadio_name }}</h4>
              <p>¿Realmente deseas eliminar este estadio?</p>
              <button type="submit" class="btn btn-danger">Eliminar Estadios</button>
              <a href="{% url 'core:list_estadios' %}" class="btn btn-warning">Cancel</a>
            </div>
          </div>
        
        
        
    </form>
{% endblock content %}  

examen2/examen2/templates/core/detail_ciudades.html
{% extends "base/base.html" %}

{% block title %}
VISTA DETALLADA DE CIUDAD
{% endblock title %}

{% block content %}
<div class="accordion" id="accordionExample">
    <div class="accordion-item">
      <h2 class="accordion-header" id="headingOne">
        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
            {{ ciudad }}
        </button>
      </h2>
      <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
        <div class="accordion-body">
          <strong>Esta es la ciudad de: {{ ciudad.nombre }}.</strong> Esta en: {{ ciudad.pais }}, <br>
        </div>
      </div>
    </div>
    <div class="accordion-item">
      <h2 class="accordion-header" id="headingTwo">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
          Details
        </button>
      </h2>
      <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
        <div class="accordion-body">
          <a href="{% url 'core:list_ciudades' %}" class="btn btn-link">Back to List</a>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

examen2/examen2/templates/core/detail_equipos.html
{% extends "base/base.html" %}

{% block title %}
VISTA DETALLADA DE EQUIPO
{% endblock title %}

{% block content %}
<div class="accordion" id="accordionExample">
    <div class="accordion-item">
      <h2 class="accordion-header" id="headingOne">
        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
            {{ equipo }}
        </button>
      </h2>
      <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
        <div class="accordion-body">
          <strong>Este es el quipo: {{ equipo.nombre }}.</strong> Son de la liga {{ equipo.liga }} , Fundacion <br>
          de la liga: {{ equipo.fundacion }}
        </div>
      </div>
    </div>
    <div class="accordion-item">
      <h2 class="accordion-header" id="headingTwo">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
          Details
        </button>
      </h2>
      <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
        <div class="accordion-body">
          <a href="{% url 'core:list_equipos' %}" class="btn btn-link">Back to List</a>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

examen2/examen2/templates/core/detail_estadios.html
{% extends "base/base.html" %}

{% block title %}
VISTA DETALLADA DE ESTADIO
{% endblock title %}

{% block content %}
<div class="accordion" id="accordionExample">
    <div class="accordion-item">
      <h2 class="accordion-header" id="headingOne">
        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
            {{ estadio }}
        </button>
      </h2>
      <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
        <div class = "accordion-body">
          <strong>Este es el estadio: {{ estadio.nombre }}.</strong> Está ubicado en {{ estadio.ciudad }}, <br>
          con una capacidad de {{ estadio.capacidad }} espectadores.
        </div>
      </div>
    </div>
    <div class="accordion-item">
      <h2 class="accordion-header" id="headingTwo">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
          Detalles
        </button>
      </h2>
      <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
        <div class="accordion-body">
          <a href="{% url 'core:list_estadios' %}" class="btn btn-link">Volver a la lista</a>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

examen2/examen2/templates/core/list_ciudades.html
{% extends "base/base.html" %}

{% block title %}
  VER LISTA CIUDADES
{% endblock title %}

{% block content %}
<br>
<hr>
    <a href="{% url 'core:create_ciudades' %}" class="btn btn-outline-success form-control">Crear una nueva ciudad</a>
    <table class="table table-striped table-hover">
        <thead>
            <th style="background-color: black; color: white; text-align: center;">ID</th>
            <th style="background-color: black; color: white; text-align: center;">NOMBRE DE LA CIUDAD</th>
            <th style="background-color: black; color: white; text-align: center;">PAÍS</th>
            <th style="background-color: black; color: white; text-align: center;"></th>
            <th style="background-color: black; color: white; text-align: center;">ACCIONES</th>
            <th style="background-color: black; color: white; text-align: center;"></th>
        </thead>
        <tbody>
            {% for ciudad in ciudades %}
                <tr>
                    <td style="background-color: black; color: white;  text-align: center;">{{ ciudad.id }}</td>
                    <td style="background-color: gray;">{{ ciudad.nombre }}</td>
                    <td style="background-color: rgb(186, 186, 186); text-align: center;">{{ ciudad.pais }}</td>
                    <td style="text-align: center;"><a href="{% url 'core:detail_ciudades' ciudad.id %}" class="btn btn-outline-info">Detalle</a></td>
                    <td style="text-align: center;"><a href="{% url 'core:update_ciudades' ciudad.id %}" class="btn btn-outline-warning">Actualizar</a></td>
                    <td style="text-align: center;"><a href="{% url 'core:delete_ciudades' ciudad.id %}" class="btn btn-outline-danger">Eliminar</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>    

{% endblock content %}

examen2/examen2/templates/core/list_equipos.html
{% extends "base/base.html" %}

{% block title %}
VER LISTA EQUIPO
{% endblock title %}

{% block content %}
<br>
<hr>
    <a href="{% url 'core:create_equipos' %}" class="btn btn-outline-success form-control">Crear un nuevo equipo</a>
    <table class="table table-striped table-hover">
        <thead>
            <th style="background-color: black; color: white; text-align: center;">ID</th>
            <th style="background-color: black; color: white; text-align: center;">NOMBRE DEL EQUIPO</th>
            <th style="background-color: black; color: white; text-align: center;">LIGA</th>
            <th style="background-color: black; color: white; text-align: center;">FUNDACIÓN</th>
            <th style="background-color: black; color: white; text-align: center;"></th>
            <th style="background-color: black; color: white; text-align: center;">ACCIONES</th>
            <th style="background-color: black; color: white; text-align: center;"></th>
        </thead>
        <tbody>
            {% for equipo in equipos %}
                <tr>
                    <td style="background-color: black; color: white;  text-align: center;">{{ equipo.id }}</td>
                    <td style="background-color: gray;">{{ equipo.nombre }}</td>
                    <td style="background-color: rgb(186, 186, 186);text-align: center; ">{{ equipo.liga }}</td>
                    <td style="background-color: rgb(214, 211, 211);text-align: center; ">{{ equipo.fundacion }}</td>
                    <td style="text-align: center;"><a href="{% url 'core:detail_equipos' equipo.id %}" class="btn btn-outline-info">Detalle</a></td>
                    <td style="text-align: center;"><a href="{% url 'core:update_equipos' equipo.id %}" class="btn btn-outline-warning">Actualizar</a></td>
                    <td style="text-align: center;"><a href="{% url 'core:delete_equipos' equipo.id %}" class="btn btn-outline-danger">Eliminar</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>    
{% endblock content %}

examen2/examen2/templates/core/list_estadios.html
{% extends "base/base.html" %}

{% block title %}
VER LISTA ESTADIO
{% endblock title %}

{% block content %}
<br>
<hr>
    <a href="{% url 'core:create_estadios' %}" class="btn btn-outline-success form-control">Crear un nuevo estadio</a>
    <table class="table table-striped table-hover">
        <thead >
            <th style="background-color: black; color: white; text-align: center;">ID</th>
            <th style="background-color: black; color: white; text-align: center;">NOMBRE DEL ESTADIO</th>
            <th style="background-color: black; color: white; text-align: center;">CIUDAD</th>
            <th style="background-color: black; color: white; text-align: center;">CAPACIDAD</th>
            <th style="background-color: black; color: white;"></th>
            <th style="background-color: black; color: white; text-align: center;">ACCIONES</th>
            <th style="background-color: black; color: white;"></th>
        </thead>
        <tbody>
            {% for estadio in estadios %}
                <tr>
                    <td style="background-color: black; color: white;  text-align: center;">{{ estadio.id }}</td>
                    <td style="background-color: gray;">{{ estadio.nombre }}</td>
                    <td style="background-color: rgb(186, 186, 186); text-align: center; ">{{ estadio.ciudad }}</td>
                    <td style="background-color: rgb(214, 211, 211); text-align: center; ">{{ estadio.capacidad }}</td>
                    <td style="text-align: center;"><a href="{% url 'core:detail_estadios' estadio.id %}" class="btn btn-outline-info">Detalle</a></td>
                    <td style="text-align: center;"><a href="{% url 'core:update_estadios' estadio.id %}" class="btn btn-outline-warning">Actualizar</a></td>
                    <td style="text-align: center;"><a href="{% url 'core:delete_estadios' estadio.id %}" class="btn btn-outline-danger">Eliminar</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>    
{% endblock content %}

examen2/examen2/templates/core/update_ciudades.html
{% extends "base/base.html" %}

{% block title %}
ACTUALIZAR VISTA DE CIUDAD
{% endblock title %}

{% block content %}
    <form action="" method="post" class="form">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-outline-primary form-control">Update Product</button>
        <br>
        <a href="{% url 'core:list_ciudades' %}" class="btn btn-outline-warning form-control">Cancel</a>
    </form>
{% endblock content %}

examen2/examen2/templates/core/update_equipos.html
{% extends "base/base.html" %}

{% block title %}
  ACTUALIZAR VISTA DE EQUIPOS
{% endblock title %}

{% block content %}
    <form action="" method="post" class="form">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-outline-primary form-control">Actualizar Equipo</button>
        <br>
        <a href="{% url 'core:list_equipos' %}" class="btn btn-outline-warning form-control">Cancel</a>
    </form>
{% endblock content %}

examen2/examen2/templates/core/update_estadios.html
{% extends "base/base.html" %}

{% block title %}
ACTUALIZAR VISTA DE ESTADIO
{% endblock title %}

{% block content %}
    <form action="" method="post" class="form">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-outline-primary form-control">Update Product</button>
        <br>
        <a href="{% url 'core:list_estadios' %}" class="btn btn-outline-warning form-control">Cancel</a>
    </form>
{% endblock content %}