portafolio2/3fplast/03fplaest/syspalest/api/urls.py
from django.urls import path

from api import views

app_name = "api"

urlpatterns = [
    
]

portafolio2/3fplast/03fplaest/syspalest/home/urls.py
from django.urls import path

from home import views

app_name = "home"

urlpatterns = [
    path('', views.Index.as_view(), name="index"),
    path('', views.Index.as_view(), name = "index_views"),
    path('About/', views.About.as_view(), name = "About_views"),
    path('Index1/', views.Index1.as_view(), name = "index1_views"),
    path('Index2/', views.Index2.as_view(), name = "index2_views"),
    path('Index3/', views.Index3.as_view(), name = "index3_views"),
    path('Index4/', views.Index4.as_view(), name = "index4_views"),
    path('Index5/', views.Index5.as_view(), name = "index5_views"),
    path('Index6/', views.Index6.as_view(), name = "index6_views"),
    path('Index7/', views.Index7.as_view(), name = "index7_views"),
    path('Index8/', views.Index8.as_view(), name = "index8_views"),
    path('Index9/', views.Index9.as_view(), name = "index9_views"),
    path('Index10/', views.Index10.as_view(), name = "index10_views"),
    path('Index11/', views.Index11.as_view(), name = "index11_views"),
    path('Index12/', views.Index12.as_view(), name = "index12_views"),
    path('Index13/', views.Index13.as_view(), name = "index13_views"),
    path('Index14/', views.Index14.as_view(), name = "index14_views"),
    path('Index15/', views.Index15.as_view(), name = "index15_views"),
    path('Index16/', views.Index16.as_view(), name = "index16_views"),
    path('Index17/', views.Index17.as_view(), name = "index17_views"),
    path('Index18/', views.Index18.as_view(), name = "index18_views"),
    path('Index19/', views.Index19.as_view(), name = "index19_views"),
    path('Index20/', views.Index20.as_view(), name = "index20_views"),
    path('new/category/', views.NewCategory.as_view(), name="newcategory"),
    path('update/category/<int:pk>/', views.UpdateCategory.as_view(), name="update_category"),
    path('detail/category/<int:pk>/', views.DetailCategory.as_view(), name="detail_category"),
    path('delete/category/<int:pk>/', views.DeleteCategory.as_view(), name="delete_category"),

   
   
]
 

portafolio2/3fplast/03fplaest/syspalest/syspalest/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include("api.urls")),
    path('core/', include("core.urls")),
    path('clients/', include("clients.urls")),
    path('providers/', include("providers.urls")),
    path('', include("home.urls")),

]

portafolio2/3fplast/03fplaest/syspalest/home/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=16, null=False, blank=False)
    bio = models.TextField(max_length=256, default="I love This App")
    timestamp = models.DateField(auto_now_add=True)
    age = models.IntegerField(default=18)
    weigth = models.FloatField(default=50.45)
    status = models.BooleanField(default=True)
    slug = models.SlugField(max_length=16)

def str(self):
    return self.name

class Category(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=32, default= "Generic Category")
    status =  models.BooleanField(default=True)

    def _str_(self):
        return self.name

class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    product_name = models.CharField(max_length=32, default= "Generic Product")
    status = models.BooleanField(default=True)
    def _str_(self):
        return self.product_name
    
class Empresa(models.Model):
    nombre = models.CharField(max_length=100)
    direccion = models.CharField(max_length=200)
    telefono = models.CharField(max_length=15)

    def _str_(self):
        return self.nombre

class Empleado(models.Model):
    user_profile = models.OneToOneField(Profile, on_delete=models.CASCADE)
    empresa = models.ForeignKey(Empresa, on_delete=models.CASCADE)
    puesto = models.CharField(max_length=50)

    def _str_(self):
        return self.user_profile.name

class ProductoEmpresa(models.Model):
    empresa = models.ForeignKey(Empresa, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=50)
    precio = models.DecimalField(max_digits=10, decimal_places=2)

    def _str_(self):
        return self.nombre

class Departamento(models.Model):
    empresa = models.ForeignKey(Empresa, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=50)

    def _str_(self):
        return self.nombre

class Proyecto(models.Model):
    empresa = models.ForeignKey(Empresa, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=100)
    descripcion = models.TextField()

    def _str_(self):
        return self.nombre

class Cliente(models.Model):
    empresa = models.ForeignKey(Empresa, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=100)
    correo = models.EmailField()

    def _str_(self):
        return self.nombre

class Proveedor(models.Model):
    empresa = models.ForeignKey(Empresa, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=100)
    telefono = models.CharField(max_length=15)

    def _str_(self):
        return self.nombre

class Evento(models.Model):
    empresa = models.ForeignKey(Empresa, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=100)
    descripcion = models.TextField()
    fecha = models.DateField()

    def _str_(self):
        return self.nombre

class Sucursal(models.Model):
    empresa = models.ForeignKey(Empresa, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=100)
    direccion = models.CharField(max_length=200)

    def _str_(self):
        return self.nombre

class Contacto(models.Model):
    empresa = models.ForeignKey(Empresa, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=100)
    correo = models.EmailField()
    telefono = models.CharField(max_length=15)

    def _str_(self):
        return self.nombre

portafolio2/3fplast/03fplaest/syspalest/home/forms.py
from django import forms
from .models import Category

class UpdateCategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = [
            "user",
            "name",
            "status"
        ]


class NewCategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = [
            "user",
            "name",
            "status"
        ]

portafolio2/3fplast/03fplaest/syspalest/home/views.py
from django.shortcuts import render
from django.views import generic
from django.urls import reverse_lazy
# Create your views here.
from .models import Category
from .forms import UpdateCategoryForm, NewCategoryForm


class Index(generic.View):
    template_name = "home/index.html"
    context = {}

    def get(self, request):
        self.context = {
            "categories": Category.objects.all()
        }
        return render (request, self.template_name, self.context)
    
class DetailCategory(generic.DetailView):
    template_name = "home/detail_category.html"
    model = Category


class UpdateCategory(generic.UpdateView):
    template_name = "home/update_category.html"
    model = Category
    form_class = UpdateCategoryForm
    success_url = reverse_lazy("home:index")



class DeleteCategory(generic.DeleteView):
    template_name = "home/delete_category.html"
    model = Category
    success_url = reverse_lazy("home:index")


class NewCategory(generic.CreateView):
    template_name = "home/newcategory.html"
    model = Category
    form_class = NewCategoryForm
    success_url = reverse_lazy("home:index")




class About(generic.View):
    template_name = "home/About.html"
    context = {}

    def get(self, request):
        return render (request, self.template_name, self.context)
    
class Index1(generic.View):
    template_name = "home/index1.html"
    context = {}

    def get(self, request):
        return render (request, self.template_name, self.context)
    
class Index2(generic.View):
    template_name = "home/index2.html"
    context = {}

    def get(self, request):
        return render (request, self.template_name, self.context)
    
class Index3(generic.View):
    template_name = "home/index3.html"
    context = {}

    def get(self, request):
        return render (request, self.template_name, self.context)
    
class Index4(generic.View):
    template_name = "home/index4.html"
    context = {}

    def get(self, request):
        return render (request, self.template_name, self.context)
    
class Index5(generic.View):
    template_name = "home/index5.html"
    context = {}

    def get(self, request):
        return render (request, self.template_name, self.context)
    
class Index6(generic.View):
    template_name = "home/index6.html"
    context = {}

    def get(self, request):
        return render (request, self.template_name, self.context)
    
class Index7(generic.View):
    template_name = "home/index7.html"
    context = {}

    def get(self, request):
        return render (request, self.template_name, self.context)
    
class Index8(generic.View):
    template_name = "home/index8.html"
    context = {}

    def get(self, request):
        return render (request, self.template_name, self.context)
    
class Index9(generic.View):
    template_name = "home/index9.html"
    context = {}

    def get(self, request):
        return render (request, self.template_name, self.context)
    
class Index10(generic.View):
    template_name = "home/index10.html"
    context = {}

    def get(self, request):
        return render (request, self.template_name, self.context)

class Index11(generic.View):
    template_name = "home/index11.html"
    context = {}

    def get(self, request):
        return render (request, self.template_name, self.context)
    
class Index12(generic.View):
    template_name = "home/index12.html"
    context = {}

    def get(self, request):
        return render (request, self.template_name, self.context)
    
class Index13(generic.View):
    template_name = "home/index13.html"
    context = {}

    def get(self, request):
        return render (request, self.template_name, self.context)
    
class Index14(generic.View):
    template_name = "home/index14.html"
    context = {}

    def get(self, request):
        return render (request, self.template_name, self.context)
    
class Index15(generic.View):
    template_name = "home/index15.html"
    context = {}

    def get(self, request):
        return render (request, self.template_name, self.context)
    
class Index16(generic.View):
    template_name = "home/index16.html"
    context = {}

    def get(self, request):
        return render (request, self.template_name, self.context)
    
class Index17(generic.View):
    template_name = "home/index17.html"
    context = {}

    def get(self, request):
        return render (request, self.template_name, self.context)
    
class Index18(generic.View):
    template_name = "home/index18.html"
    context = {}

    def get(self, request):
        return render (request, self.template_name, self.context)
    
class Index19(generic.View):
    template_name = "home/index19.html"
    context = {}

    def get(self, request):
        return render (request, self.template_name, self.context)
    
class Index20(generic.View):
    template_name = "home/index20.html"
    context = {}

    def get(self, request):
        return render (request, self.template_name, self.context)

portafolio2/3fplast/03fplaest/syspalest/templates/home/About.html
<h1>QUE BENDICION</h1>

portafolio2/3fplast/03fplaest/syspalest/templates/home/delete_category.html
{% extends 'base/base.html' %}

{% block title %}Delete Category View {% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
            ¿ Realmente deseas eliminar esta categoria: <strong>{{object}}??</strong>
            <a href="{% url 'home:index' %}" class="btn btn-outline-info">Cancel</a>
            <button type="submit" class="btn btn-outline-danger">Delete</button>
    </form>
{% endblock content %}

portafolio2/3fplast/03fplaest/syspalest/templates/home/index.html
{% extends 'base/base.html' %}

{% block title %}Index View{% endblock title %}

{% block content %}
    <table class="table table-striped">
        <thead>
            <th>ID</th>
            <th>NAME</th>
            <th>STATUS</th>
            <th>ACTIONS</th>
        </thead>
        <tbody>
            {% for category in categories %}
            <tr>
                <td>{{ category.id }}</td>
                <td>{{ category.name }}</td>
                <td>{{ category.status }}</td>
                <td><a href="{% url 'home:detail_category' category.id %}" class="btn btn-outline-info">Detail</a></td>
                <td><a href="{% url 'home:update_category' category.id %}" class="btn btn-outline-warning">Update</a></td>
                <td><a href="{% url 'home:delete_category' category.id %}" class="btn btn-outline-danger">Delete</a></td>
            </tr>
            {% endfor %}
        </tbody>
        
    </table>
{% endblock content %}

portafolio2/3fplast/03fplaest/syspalest/templates/home/index11.html
<h1>PRUBE13</h1>

portafolio2/3fplast/03fplaest/syspalest/templates/home/index15.html
<h1>PRUBE17</h1>

portafolio2/3fplast/03fplaest/syspalest/templates/home/index18.html
<h1>PRUBE20</h1>

portafolio2/3fplast/03fplaest/syspalest/templates/home/index19.html
<h1>PRUBE21</h1>

portafolio2/3fplast/03fplaest/syspalest/templates/home/index20.html
<h1>PRUBE22</h1>

portafolio2/3fplast/03fplaest/syspalest/templates/home/index3.html
<H1>PRUEBA5</H1>

portafolio2/3fplast/03fplaest/syspalest/templates/home/index5.html
<H1>PRUEBA7</H1>

portafolio2/3fplast/03fplaest/syspalest/templates/home/index6.html
<H1>PRUEBA8</H1>

portafolio2/3fplast/03fplaest/syspalest/templates/home/index8.html
<H1>PRUEBA10</H1>

portafolio2/3fplast/03fplaest/syspalest/templates/home/index9.html
<H1>PRUEBA11</H1>

portafolio2/3fplast/03fplaest/syspalest/templates/home/newcategory.html
{% extends 'base/base.html' %}

{% block title %}New Category View {% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form }}
        <a href="{% url 'home:index'%}" class="btn btn-outline-info">Cancel</a>
        <button type="submit" class="btn btn-outline-success">New Category</button>
    </form>
{% endblock content %}