portafolio2/proyectomx-discovery/core/urls.py
from django.urls import path

from core import views

app_name = "core"

urlpatterns = [
    path('create/product/', views.CreateProduct.as_view(), name="create_product"),
    path('list/product/', views.ListProduct.as_view(), name="list_product"),
    path('detail/product/<int:pk>/', views.DetailProduct.as_view(), name="detail_product"),
    path('update/product/<int:pk>/', views.UpdateProduct.as_view(), name="update_product"),
    path('delete/product/<int:pk>/', views.DeleteProduct.as_view(), name="delete_product"),
]

portafolio2/proyectomx-discovery/proyectomxdicovery/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path('core/', include("core.urls")),
]

portafolio2/proyectomx-discovery/core/models.py
from django.db import models

from django.contrib.auth.models import User
# Create your models here.

class Category(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    category_name = models.CharField(max_length=32, default="Generic Category Name")
    description = models.CharField(max_length=256, default="Generic Category Description")
    timestamp = models.DateField(auto_now_add=True)
    update_category = models.DateField(auto_now=True, auto_now_add=False)
    status = models.BooleanField(default=True)
    slug = models.SlugField(max_length=16)

    def __str__(self):
        return self.category_name
    

class SubCategory(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    subcategory_name = models.CharField(max_length=32, default="Generic Category Name")
    description = models.CharField(max_length=256, default="Generic Category Description")
    timestamp = models.DateField(auto_now_add=True)
    update_category = models.DateField(auto_now=True, auto_now_add=False)
    status = models.BooleanField(default=True)
    slug = models.SlugField(max_length=16)

    def __str__(self):
        return self.subcategory_name



class Brand(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    brand_name = models.CharField(max_length=32, default="Generic Category Name")
    description = models.CharField(max_length=256, default="Generic Category Description")
    timestamp = models.DateField(auto_now_add=True)
    update_category = models.DateField(auto_now=True, auto_now_add=False)
    status = models.BooleanField(default=True)
    slug = models.SlugField(max_length=16)

    def __str__(self):
        return self.brand_name
    

class Product(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    subcategory = models.ForeignKey(SubCategory, on_delete=models.CASCADE)
    product_name = models.CharField(max_length=32, default="Generic Product Name")
    description = models.CharField(max_length=256, default="Generic Product Description")
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE)
    stock = models.IntegerField(default=0)
    price_cost = models.FloatField(default=0.0)
    image = models.ImageField(upload_to='products_images', blank=True, null=True) # configurar un servidor de media
    timestamp = models.DateField(auto_now_add=True)
    update_category = models.DateField(auto_now=True, auto_now_add=False)
    status = models.BooleanField(default=True)
    slug = models.SlugField(max_length=16)

    def __str__(self):
        return self.product_name

portafolio2/proyectomx-discovery/core/forms.py
from django import forms

from .models import Product

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = [
            "user",
            "subcategory",
            "product_name",
            "description",
            "brand",
            "stock",
            "price_cost",
            "image",
            "status",
            "slug"
        ] # fields = "__all__"
        # exclude = ["timestamp", "updated"]
        widgets = {
            "user": forms.Select(attrs={"class":"form-select form-control"}),
            "subcategory": forms.Select(attrs={"class":"form-select form-control"}),
            "product_name": forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe el nombre del Producto"}),
            "description": forms.Textarea(attrs={"type":"text", "class":"form-control", "rows":3, "placeholder":"Escribe la descripcion del Producto"}),
            "brand": forms.Select(attrs={"class":"form-select form-control"}),
            "stock": forms.TextInput(attrs={"type":"number", "class":"form-control"}),
            "price_cost": forms.TextInput(attrs={"type":"number", "class":"form-control"}),
            "image": forms.FileInput(attrs={"type":"file", "class":"form-control"}),
            "status": forms.CheckboxInput(attrs={"type":"checkbox"}),
            "slug": forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe el codigo de busqueda del Producto"})
        }



class UpdateProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = [
            "user",
            "subcategory",
            "product_name",
            "description",
            "brand",
            "stock",
            "price_cost",
            "image",
            "status",
            "slug"
        ] # fields = "__all__"
        # exclude = ["timestamp", "updated"]
        widgets = {
            "user": forms.Select(attrs={"class":"form-select form-control"}),
            "subcategory": forms.Select(attrs={"class":"form-select form-control"}),
            "product_name": forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe el nombre del Producto"}),
            "description": forms.Textarea(attrs={"type":"text", "class":"form-control", "rows":3, "placeholder":"Escribe la descripcion del Producto"}),
            "brand": forms.Select(attrs={"class":"form-select form-control"}),
            "stock": forms.TextInput(attrs={"type":"number", "class":"form-control"}),
            "price_cost": forms.TextInput(attrs={"type":"number", "class":"form-control"}),
            "image": forms.FileInput(attrs={"type":"file", "class":"form-control"}),
            "status": forms.CheckboxInput(attrs={"type":"checkbox"}),
            "slug": forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe el codigo de busqueda del Producto"})
        }

portafolio2/proyectomx-discovery/core/views.py
from django.shortcuts import render

from django.views import generic
from django.urls import reverse_lazy

from .models import Category, SubCategory, Brand, Product
from .forms import ProductForm, UpdateProductForm

# Create your views here.

# # # # #  C R U D P R O D U C T S # # # # # 

## Create
class CreateProduct(generic.CreateView):
    template_name = "core/create_product.html"
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy("core:list_product")


## Retrieve
# List
class ListProduct(generic.View):
    template_name = "core/list_product.html"
    context = {}

    def get(self, request, *args, **kwargs):
        products = Product.objects.filter(status=True)
        self.context = {
            "products": products
        }
        return render(request, self.template_name, self.context)

# Detail
class DetailProduct(generic.View):
    template_name = "core/detail_product.html"
    context = {}

    def get(self, request, pk, *args, **kwargs):
        product = Product.objects.get(pk=pk)
        self.context = {
            "product": product
        }
        return render(request, self.template_name,self.context)



## Update
class UpdateProduct(generic.UpdateView):
    template_name = "core/update_product.html"
    model = Product
    form_class = UpdateProductForm
    success_url = reverse_lazy("core:list_product")


## Delete
class DeleteProduct(generic.DeleteView):
    template_name = "core/delete_product.html"
    model = Product
    success_url = reverse_lazy("core:list_product")

portafolio2/proyectomx-discovery/templates/core/create_product.html
{% extends "base/base.html" %}

{% block title %}
  CREATE PRODUCT VIEW
{% endblock title %}

{% block content %}
    <form action="" method="post" class="form">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-outline-success form-control">Create Product</button>
        <br>
        <a href="{% url 'core:list_product' %}" class="btn btn-outline-warning form-control">Cancel</a>
    </form>
{% endblock content %}

portafolio2/proyectomx-discovery/templates/core/delete_product.html
{% extends "base/base.html" %}

{% block title %}
  DELETE PRODUCT VIEW
{% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <div class="card text-white bg-primary mb-3" style="max-width: 20rem;">
            <div class="card-header">Delete Product</div>
            <div class="card-body">
              <h4 class="card-title">{{ object.product_name }}</h4>
              <p>¿Realmente deseas eliminar este producto?</p>
              <button type="submit" class="btn btn-danger">Delete Product</button>
              <a href="{% url 'core:list_product' %}" class="btn btn-warning">Cancel</a>
            </div>
          </div>
        
        
        
    </form>
{% endblock content %}  

portafolio2/proyectomx-discovery/templates/core/detail_product.html
{% extends "base/base.html" %}

{% block title %}
  PRODUCT DETAIL VIEW
{% endblock title %}

{% block content %}
<div class="accordion" id="accordionExample">
    <div class="accordion-item">
      <h2 class="accordion-header" id="headingOne">
        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
            {{ product }}
        </button>
      </h2>
      <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
        <div class="accordion-body">
          <strong>This is the Product: {{ product.product_name }}.</strong> It is shown: {{ product.description }}, <br>
          timestamp: {{ product.timestamp}} --- category: {{ product.subcategory }}
        </div>
      </div>
    </div>
    <div class="accordion-item">
      <h2 class="accordion-header" id="headingTwo">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
          Brand: {{ product.brand }}
          
        </button>
      </h2>
      <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
        <div class="accordion-body">
          <strong>This is the Status: {{ product.status }}.</strong> <br>
          Stock: {{ product.stock }}
          <hr>
          <a href="{% url 'core:list_product' %}" class="btn btn-link">back to list</a>
        </div>
      </div>
    </div>
    
  </div>
  
{% endblock content %}

portafolio2/proyectomx-discovery/templates/core/list_product.html
{% extends "base/base.html" %}

{% block title %}
  LIST PRODUCT VIEW
{% endblock title %}

{% block content %}
<br>
<hr>
    <a href="{% url 'core:create_product' %}" class="btn btn-outline-success form-control">Create a New Product</a>
    <table class="table table-striped table-hover">
        <thead>
            <th>ID</th>
            <th>PRODUCT NAME</th>
            <th>SUBCATEGORY</th>
            <th>DESCRIPTION</th>
            <th>STATUS</th>
            <th></th>
            <th>ACTIONS</th>
            <th></th>
        </thead>
        <tbody>
            {% for product in products %}
                <tr>
                    <td>{{ product.id }}</td>
                    <td>{{ product.product_name }}</td>
                    <td>{{ product.subcategory }}</td>
                    <td>{{ product.description }}</td>
                    <td>{{ product.status }}</td>
                    <td><a href="{% url 'core:detail_product' product.id %}" class="btn btn-outline-info"> Detail </a></td>
                    <td><a href="{% url 'core:update_product' product.id %}" class="btn btn-outline-warning"> Update </a></td>
                    <td><a href="{% url 'core:delete_product' product.id %}" class="btn btn-outline-danger"> Delete </a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>    

{% endblock content %}

portafolio2/proyectomx-discovery/templates/core/update_product.html
{% extends "base/base.html" %}

{% block title %}
  UPDATE PRODUCT VIEW
{% endblock title %}

{% block content %}
    <form action="" method="post" class="form">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-outline-primary form-control">Update Product</button>
        <br>
        <a href="{% url 'core:list_product' %}" class="btn btn-outline-warning form-control">Cancel</a>
    </form>
{% endblock content %}