examen2/examen2/NFLPR/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path('core/', include("core.urls")),
]

examen2/examen2/core/urls.py
from django.urls import path

from core import views

app_name = "core"

urlpatterns = [
    path('create/ciudades/', views.CreateCiudades.as_view(), name="create_ciudades"),
    path('list/ciudades', views.ListCiudades.as_view(), name="list_ciudades"),
    path('detail/ciudades/<int:pk>/', views.DetailCiudades.as_view(), name="detail_ciudades"),
    path('update/ciudades/<int:pk>/', views.UpdateCiudades.as_view(), name="update_ciudades"),
    path('delete/ciudades/<int:pk>/', views.DeleteCiudades.as_view(), name="delete_ciudades"),

    ####URLS EQUIPOS

    path('create/equipos/', views.CrearEquipo.as_view(), name="create_equipos"),
    path('list/equipos/', views.ListarEquipos.as_view(), name="list_equipos"),
    path('detail/equipos/<int:pk>/', views.DetalleEquipo.as_view(), name="detail_equipos"),
    path('update/equipos/<int:pk>/', views.ActualizarEquipo.as_view(), name="update_equipos"),
    path('delete/equipos/<int:pk>/', views.EliminarEquipo.as_view(), name="delete_equipos"),

    ###URLS ESTADIOS

    path('create/estadios/', views.CrearEstadio.as_view(), name="create_estadios"),
    path('list/estadios/', views.ListarEstadios.as_view(), name="list_estadios"),
    path('detail/estadios/<int:pk>/', views.DetalleEstadio.as_view(), name="detail_estadios"),
    path('update/estadios/<int:pk>/', views.ActualizarEstadio.as_view(), name="update_estadios"),
    path('delete/estadios/<int:pk>/', views.EliminarEstadio.as_view(), name="delete_estadios"),

]

examen2/examen2/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title%}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
   
</head>
<body style="min-height: 100vh;
position: relative;">

  <style>
    .container{
      background-color: rgb(255, 255, 255);
      text-decoration: rgb(0, 0, 0);
    }

    nav{
            background-color: rgb(2, 217, 232);
            text-align: right;            
        }


    
  </style>

    <div class="container">
        <div class="row">
            <div class="col">
              <nav class="navbar navbar-expand-lg custom-navbar">
                    <div class="container-fluid">
                      <a class="navbar-brand" style="color: brown;" href="#">EXAMENPR2</a>
                      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                      </button>
                      <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                          <li class="nav-item">
                            <a class="nav-link active" aria-current="page" style="color: rgb(0, 0, 0);" href="{% url 'core:list_ciudades' %}">Inicio</a>
                          </li>                          
                          <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                              Equipos
                            </a>
                            <ul class="dropdown-menu">
                              <li><a class="dropdown-item"   href="{% url 'core:create_equipos' %}">Nuevo Equipo</a></li>
                              <li><a class="dropdown-item" href="{% url 'core:list_equipos' %}">Lista de Equipos</a></li>
                              <li><hr class="dropdown-divider"></li>
                              <li><a class="dropdown-item" href="#">Actualizar Equipo</a></li>
                              <li><a class="dropdown-item" href="#">Eliminar Equipo</a></li>
                            </ul>
                          </li>
                          <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                              Estadios
                            </a>
                            <ul class="dropdown-menu">
                              <li><a class="dropdown-item" href="{% url 'core:create_estadios' %}">Nuevo Estadio</a></li>
                              <li><a class="dropdown-item" href="{% url 'core:list_estadios' %}">Lista de Estadios</a></li>
                              <li><hr class="dropdown-divider"></li>
                              <li><a class="dropdown-item" href="#">Actualizar Estadios</a></li>
                              <li><a class="dropdown-item" href="#">Eliminar Estadios</a></li>
                            </ul>
                          </li>
                          <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                              Ciudades
                            </a>
                            <ul class="dropdown-menu">
                              <li><a class="dropdown-item" href="{% url 'core:create_ciudades' %}">Nueva Ciudad</a></li>
                              <li><a class="dropdown-item" href="{% url 'core:list_ciudades' %}">Lista Ciudades</a></li>
                              <li><hr class="dropdown-divider"></li>
                              <li><a class="dropdown-item" href="#">Actualizar Ciudades</a></li>
                              <li><a class="dropdown-item" href="#">Eliminar Ciudades</a></li>
                            </ul>
                          </li>                 
                        </ul>
                        <form class="d-flex" role="search">
                          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                          <button class="btn btn-outline-success" type="submit">Search</button>
                        </form>
                      </div>
                    </div>
                  </nav>
            </div>
        </div>

        <div class="row">
                <div class="col">
                    {% block content %}
                    {% endblock content %}
                </div>
        </div>

        <div class="row">
            <div class="col">

            </div>
            <div class="col">

            </div>
        </div>
    </div>
    
    <footer class="bg-light text-center text-lg-start " style="padding-bottom: 50px;">
      <div class="text-center p-3" style="background-color: rgb(2, 217, 232); position: absolute;bottom: 0;
      width: 100%;">
       Pulido Larios Cristopher
      </div>
    </footer>
   
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>